### ISSUE TITLE
### Forked to github.com/go-mail/gomail ###

### ISSUE THREAD

**Issue by pedromorgan** [go-gomail/gomail#105]
First read issue #104 (maintainer missing)

So I've forked to [github.com/go-mail/gomail](https://github.com/go-mail/gomail) so can move forward, and am looking through the pull requests, issue's etc.

Can I suggest users come forward so we can add to the "organisation", and thereby not have this fork problem again.

**Comment by pedromorgan** [comment]
moot

**Comment by Neustradamus** [comment]
Dear all, it is possible to change your code?
- https://github.com/go-mail/mail
- https://github.com/go-gomail/gomail

It has been unmaintained and maybe vulnerabilities :/

There are:
- https://github.com/xhit/go-simple-mail from @xhit
- https://github.com/wneessen/go-mail from @wneessen

**Comment by Neustradamus** [comment]
Dear all, it is possible to change your code?
Change from here:
- https://github.com/go-gomail/gomail
- https://github.com/go-gomail/gomail/issues/188
- https://github.com/go-mail/mail
- https://github.com/Shopify/gomail
- https://github.com/Shopify/gomail/issues/59
- https://github.com/ory/mail

It has been unmaintained and maybe one or more vulnerabilities :/

There are:
- https://github.com/xhit/go-simple-mail from @xhit
- https://github.com/wneessen/go-mail from @wneessen

Linked to:
- https://github.com/go-gomail/gomail/issues/182
- https://github.com/go-gomail/gomail/issues/163
- https://github.com/go-gomail/gomail/issues/142
- https://github.com/go-gomail/gomail/issues/108
- https://github.com/go-gomail/gomail/issues/104
- https://github.com/go-gomail/gomail/issues/105
- https://github.com/go-gomail/gomail/issues/94
- https://github.com/go-mail/mail/issues/78
- https://github.com/go-mail/mail/issues/73
- https://github.com/go-mail/mail/issues/61
