### ISSUE TITLE
There is no NewDialer method

### ISSUE THREAD

**Issue by nmsobri** [go-gomail/gomail#117]
```
gomail.NewDialer("smtp.example.com", 587, "user", "pass")
```

Unresolve reference to NewDialer.I can only call :

```
gomail.NewPlainDialer("smtp.example.com", 587, "slier81", "123456")
```

Is the documentation deprecated? Or am I doing something wrong?
Please advise

**Comment by ghost** [comment]
For some reason you are getting the V1 branch which doesn't contain the new "gomail.NewDialer" method

**Comment by pedromorgan** [comment]
Note: https://github.com/go-gomail/gomail/issues/108

**Comment by nmsobri** [comment]
thx @pedromorgan
