### ISSUE TITLE
 Is there a limit to the number of emails sent?

### ISSUE THREAD

**Issue by lizikeepfighting** [go-gomail/gomail#118]
Can this be used to send a verification code for registered email?
When there are many users, the frequency of sending tests will be very frequent. Is this service suitable for this?

Thanks a lot

**Comment by pedromorgan** [comment]
This is for developers, and how to send emails across the interwebs, part of the plumbing and is code for running.

U can probaly send a million++++ emails a second if u got a connection..

What u probably want is something like 
- https://mailchimp.com
- https://free-mega-mailer.com

**Comment by pedromorgan** [comment]
https://github.com/go-gomail/gomail/issues/108

hey @BigWhiteEat  can u do the future a favour and close this "issue".. it would help us..
and any other questions, then no problem.. in this thread
