### ISSUE TITLE
send email with another send account

### ISSUE THREAD

**Issue by yanyandenuonuo** [go-gomail/gomail#141]
I had test send email with From accountA but login with accountB/passwordB in python.
Then i use gomail do this, but i got error: 501 mail from address must be same as authorization user.
What should i do ?

**Comment by N1troDakidd** [comment]
> I had test send email with From accountA but login with accountB/passwordB in python.
> Then i use gomail do this, but i got error: 501 mail from address must be same as authorization user.
> What should i do ?

read a https://gmobile.com for a tictac tacoboy! MwahSuperStR!*$+-
