### ISSUE TITLE
Export to []byte

### ISSUE THREAD

**Issue by chrneumann** [go-gomail/gomail#15]
It would be nice to be able to export gomail.Message to []byte. I would suggest a function Raw() []byte on Message.

I could implement this and make a pull request.

**Comment by nvcnvn** [comment]
Any hints to implement this feature?
I really want to use this package to send mail with Amazon SES using raw data.

Thanks!

**Comment by chrneumann** [comment]
I'm not sure what you want to do, but you could try using a custom SendMailFunc.

**Comment by chrneumann** [comment]
For an example, see my SendMailFunc https://github.com/monsti/monsti/blob/master/api/service/monsti.go#L556
and its use here:
https://github.com/monsti/monsti/blob/master/core/monsti-daemon/session.go#L144

**Comment by nvcnvn** [comment]
I think SendMailFunc quite different from my need.
AWS allow you to post a raw email message to SES API via HTTP:
http://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-raw.html

**Comment by alexcesaro** [comment]
chrneumann is right, that's the best way to do it. A Message instance can represent different raw emails when [the `Bcc` field is filled](https://github.com/go-gomail/gomail/blob/4fcb155d12aa4486b9c00602531ff6bcb98ebd82/mailer.go#L93). So it cannot simply be exported to a slice of bytes.

Use a `SendMailFunc` instead.
