### ISSUE TITLE
send email with no auth

### ISSUE THREAD

**Issue by ipartner** [go-gomail/gomail#17]
Hi.
I need to use a relay server to send email. there is no user and no sender account. 
but the library looks like its you need to auth every time.

**Comment by alexcesaro** [comment]
Can you detail a bit more? How do you send emails exactly?

**Comment by ipartner** [comment]
We need to send mail w/o auth using your library. But looking at the api it only offers send via auth( may I be wrong)

So
There is a way just to send a mail via a relay server without any auth?

Enviado desde mi iPhone

**Comment by alexcesaro** [comment]
Then you should create a mailer using [NewCustomMailer](https://godoc.org/gopkg.in/gomail.v1#NewCustomMailer) and use `nil` as an smtp.Auth.

**Comment by alexcesaro** [comment]
package main

import (
    "gopkg.in/gomail.v2-unstable"
)

func main() {
    m := gomail.NewMessage()
    m.SetHeader("From", "from@example.com")
    m.SetHeader("To", "to@example.com")
    m.SetHeader("Subject", "Test")
    m.SetBody("text/html", "Test")

    d := &gomail.Dialer{Host: "smtp.example.org", Port: 587}
    if err := d.DialAndSend(m); err != nil {
        panic(err)
    }
}

**Comment by alexcesaro** [comment]
Hello, it would be cool if you tried Gomail v2 (still unstable) and tell me if it works:

```go
package main

import (
	"gopkg.in/gomail.v2-unstable"
)

func main() {
	m := gomail.NewMessage()
	m.SetHeader("From", "from@example.com")
	m.SetHeader("To", "to@example.com")
	m.SetHeader("Subject", "Test")
	m.SetBody("text/html", "Test")

	d := &gomail.Dialer{Host: "smtp.example.org", Port: 587}
	if err := d.DialAndSend(m); err != nil {
		panic(err)
	}
}
```

**Comment by jasonwee** [comment]
> Hello, it would be cool if you tried Gomail v2 (still unstable) and tell me if it works:
> 
> ```go
> package main
> 
> import (
>     "gopkg.in/gomail.v2-unstable"
> )
> 
> func main() {
>     m := gomail.NewMessage()
>     m.SetHeader("From", "from@example.com")
>     m.SetHeader("To", "to@example.com")
>     m.SetHeader("Subject", "Test")
>     m.SetBody("text/html", "Test")
> 
>     d := &gomail.Dialer{Host: "smtp.example.org", Port: 587}
>     if err := d.DialAndSend(m); err != nil {
>         panic(err)
>     }
> }
> ```

you might want to add the following InsecureSkipVerify to true when sending to localhost because normally localhost dont have a ssl cert.

```
d := &gomail.Dialer{Host: "smtp.example.org", Port: 25}
d.TLSConfig = &tls.Config{InsecureSkipVerify: true}
```

if you don't add that, you will get this

```
panic: x509: certificate is not valid for any names, but wanted to match localhost
```
