### ISSUE TITLE
Where to Report Vulnerabilities?

### ISSUE THREAD

**Issue by motoyasu-saburi** [go-gomail/gomail#188]
I found a vulnerability, 
is there a place to report it?

**Comment by solodyagin** [comment]
see https://github.com/go-gomail/gomail/issues/182 ;-((

**Comment by motoyasu-saburi** [comment]
@solodyagin 
Thank you for the sharing information.

**Comment by Neustradamus** [comment]
Dear all, it is possible to change your code?
Change from here:
- https://github.com/go-gomail/gomail
- https://github.com/go-gomail/gomail/issues/188
- https://github.com/go-mail/mail
- https://github.com/Shopify/gomail
- https://github.com/Shopify/gomail/issues/59
- https://github.com/ory/mail

It has been unmaintained and maybe one or more vulnerabilities :/

There are:
- https://github.com/xhit/go-simple-mail from @xhit
- https://github.com/wneessen/go-mail from @wneessen

Linked to:
- https://github.com/go-gomail/gomail/issues/182
- https://github.com/go-gomail/gomail/issues/163
- https://github.com/go-gomail/gomail/issues/142
- https://github.com/go-gomail/gomail/issues/108
- https://github.com/go-gomail/gomail/issues/104
- https://github.com/go-gomail/gomail/issues/105
- https://github.com/go-gomail/gomail/issues/94
- https://github.com/go-mail/mail/issues/78
- https://github.com/go-mail/mail/issues/73
- https://github.com/go-mail/mail/issues/61

**Comment by Neustradamus** [comment]
@motoyasu-saburi: Can you publish all gomail vulnerabilities?

cc: @unknwon

Linked to:
- https://github.com/Shopify/gomail/issues/59
- https://github.com/go-gomail/gomail/issues/188
- https://github.com/go-gomail/gomail/issues/190
