### ISSUE TITLE
Several people on Bcc? 

### ISSUE THREAD

**Issue by siritinga** [go-gomail/gomail#19]
Hi!

Currently, I'm using `msg.SetAddressHeader("Bcc", emailBcc, "bcc")` to copy someone while hiding its address. Is the right way to do that? How can I copy more people? 

Thanks!

**Comment by alexcesaro** [comment]
Yes that is the right way.
To add more people you can use `msg.SetAdressHeader` multiple times or you can do:

```go
SetHeader("Bcc", "alice@example.com", "bob@example.com", "carol@example.com")
```

**Comment by siritinga** [comment]
Can I use SetAddressHeader multiple times? From the code it looks like every call with the same field string will replace previous entry in the header map.

**Comment by alexcesaro** [comment]
Yes you're right. So use the second method instead.

**Comment by siritinga** [comment]
Thanks! and thanks for gomail, is great :+1:

**Comment by sepehrmm** [comment]
Hi @alexcesaro 
What if SetAddressHeader is changed to append instead of replace?
I don't think it cause any impact.
