### ISSUE TITLE
[feature] Flag to ignore invalid address error

### ISSUE THREAD

**Issue by RandalTeng** [go-gomail/gomail#191]
Can smtp client add a flag option set to ignore error that address is invalid?
In my php program, the phpmail ignore the option in default, I want set gomail set it too, it could set to false as default, make the behavior is extraly like before.
Like this:
``` go
dialer := gomail.NewDialer(conf.SMTP.Host, conf.SMTP.Port, conf.SMTP.Username, conf.SMTP.Password)
dialer.SetIgnoreAddressInvalid(true) // if have not this call, the behavior should same as before.
err := dialer.DialAndSend(mail)
if err != nil {
  return err
}
```

**Comment by RandalTeng** [comment]
Seem the go standard SMTP client not implement it as a flag, ignore this issue.

**Comment by wneessen** [comment]
This project is not maintained anymore. The owned unfortunately passed away. You might wanna have a look at [go-mail](https://github.com/wneessen/go-mail) instead.

**Comment by RandalTeng** [comment]
Thanks for the reply, I will check it out.
