### ISSUE TITLE
how to set timeout when send

### ISSUE THREAD

**Issue by imqishi** [go-gomail/gomail#197]
sometimes I found that send will block, so is there any way to set timeout to avoid program hang?

**Comment by wneessen** [comment]
To my knowledge the package does not support timeouts. Unfortunately also [the maintainer has sadly passed away](https://github.com/go-gomail/gomail/issues/182).

You might want to consider checking [wneessen/go-mail](https://github.com/wneessen/go-mail) which has `context.Context` support.

**Comment by imqishi** [comment]
> To my knowledge the package does not support timeouts. Unfortunately also [the maintainer has sadly passed away](https://github.com/go-gomail/gomail/issues/182).
> 
> You might want to consider checking [wneessen/go-mail](https://github.com/wneessen/go-mail) which has `context.Context` support.

Thanks for your help, I will try it ~
