### ISSUE TITLE
Need to encode headers when special disallowed characters are present

### ISSUE THREAD

**Issue by jfroy** [go-gomail/gomail#23]
For example, if the character "," is present in a header field, it must be encoded because it is the address separator character in the address-list (RFC 2822) production rule.

**Comment by alexcesaro** [comment]
This is on purpose. Can you show your code or describe what your trying to
do?

**Comment by OVYA** [comment]
Hello,
I think I have encountered this problem with the character sequence \\\\ in the To part. Here is an ECM 
```go
package main

import (
	"crypto/tls"

	"gopkg.in/gomail.v1"
)

func main() {
	msg := gomail.NewMessage()
	msg.SetHeader("From", "pi@test.fr")
	msg.SetHeader("To", msg.FormatAddress("pi@localhost", "X\\XXXXX"))
	msg.SetHeader("Subject", "Test")
	msg.SetBody("text/html", "Hello <b>Bob</b> and <i>Cora</i>!")

	mailer := gomail.NewMailer("127.0.0.1", "no-reply@test.com", "", 25,
		gomail.SetTLSConfig(&tls.Config{InsecureSkipVerify: true}))

	if err := mailer.Send(msg); err != nil {
		panic(err)
	}
}
```

This fails with message `panic: mail: no angle-addr`.  Same error replacing \\\\ by a comma.

**Comment by jfroy** [comment]
Yeah I ran into this trying to send an email to someone with a ',' in their name.

**Comment by alexcesaro** [comment]
Thanks guys! I just fixed that bug by quoting names in address headers.
