### ISSUE TITLE
Offer way to encode headers and body separately

### ISSUE THREAD

**Issue by jfroy** [go-gomail/gomail#24]
In some conditions, BASE64 encoding of headers is required, for example when a " character is present in a To: or From: address. However, setting BASE64 as the encoding will also cause the body to be BASE64 encoded, which will lead many spam filters to flag the message as spam. This is true at least for SpamSieve, but possibly many others.

**Comment by alexcesaro** [comment]
Thanks a lot for detailing this issue. Gomail now automatically use base64 encoding when the name in an address header needs RFC 2047 encoding and has special characters.
