### ISSUE TITLE
No way to set more than one address header with proper encoding

### ISSUE THREAD

**Issue by jfroy** [go-gomail/gomail#26]
With the current API, you can call SetAddressHeader once, which will pass the input through FormatAddress and set the header, or you can format multiple addresses with FormatAddress and then set the address header with a slice containing the formatted addresses.

However, the second method does not work because FormatAddress may encoding an address as needed. Then, SetHeader will encode the address again, yielding a twice-encoded final value.

**Comment by alexcesaro** [comment]
I do not have this issue. Could you show me your code?
