### ISSUE TITLE
Multiple bodies

### ISSUE THREAD

**Issue by EtienneBruines** [go-gomail/gomail#30]
Its often convenient to send both `text/html` and `text/plain`: pretty emails for those that support it, and basic emails for those that don't. 

```go
msg := gomail.NewMessage()

msg.SetBody("text/plain", "Hello!")
msg.SetBody("text/html", "<b>Hello!</b>")
```

However, the second `SetBody`, replaces the first.

**Comment by EtienneBruines** [comment]
I managed to fix this, by changing in `gomail.go` (lines 175+)
```go
// SetBody sets the body of the message.
func (msg *Message) SetBody(contentType, body string) {
	msg.parts = []part{
		part{
			contentType: contentType,
			body:        bytes.NewBufferString(body),
		},
	}
}
```

to 
```go
// SetBody sets the body of the message.
func (msg *Message) SetBody(contentType, body string) {
	msg.parts = append(msg.parts, []part{
		part{
			contentType: contentType,
			body:        bytes.NewBufferString(body),
		},
	}...)
}
```

However, the name `SetBody` does not seem appropriate anymore. Perhaps this should be renamed to `AddBody` in this case, or another function all together (`SetBody` with the original behavior, and `AddBody` with the new behavior. ) Or perhaps `AppendBody`

Any thoughts?

**Comment by alexcesaro** [comment]
Hi, [AddAlternative](https://godoc.org/gopkg.in/gomail.v1#Message.AddAlternative) is exactly what you are looking for.

**Comment by EtienneBruines** [comment]
Did not see that one! Thank you.
