### ISSUE TITLE
anonymous relay

### ISSUE THREAD

**Issue by GuyBrand** [go-gomail/gomail#32]
Hi .

I am trying to relay on a server with no authentication .
using a telnet client , I can simply :
1. telnet MyServer MyPort
2. Helo
3. MAIL FROM: me@gmail.com
4. RCPT TO: you@gmail.com
5. SUBJECT:how are you?
6. period (.)

I tried to create an Auth with Start function that returns immediately , with empty return value , or "MAIL FROM:" , but I guess no matter what I do , smtp package will go through :
code, msg64, err := c.cmd(0, "AUTH %s %s", mech, resp64)
that the server will decline .

Do you have an idea for doing anonymous connection/ESMTP AUTH .
my best help so far was http://www.fehcom.de/qmail/smtpauth.html

Thanks .

**Comment by alexcesaro** [comment]
Have you tried using NewCustomMailer with a nil Auth?

**Comment by GuyBrand** [comment]
Nop , same error L

 

x509: certificate signed by unknown authority

**Comment by alexcesaro** [comment]
Have you tried what's in the readme? https://github.com/go-gomail/gomail#x509-certificate-signed-by-unknown-authority

**Comment by GuyBrand** [comment]
Yes , no help there .

 

Notice that if I use NewMailer , I must empty the UN/PW 

 

mailer := gomail.NewMailer("mysmtp.net", "", "", 25, gomail.SetTLSConfig(&tls.Config{InsecureSkipVerify: true}))

 

guy .

**Comment by alexcesaro** [comment]
What is the error in this case?

You should try using both NewCustomMailer with nil Auth and SetTLSConfig.

**Comment by GuyBrand** [comment]
Both return same error :

x509: certificate signed by unknown authority

**Comment by GuyBrand** [comment]
Hi .

The  Client's IT has sent me a CERT file thinking it may solve the situation .
I dont know if it has anything to do with it , but now , when I :
mailer := gomail.NewMailer("serverIp", "", "", 25, gomail.SetTLSConfig(&tls.Config{InsecureSkipVerify: true}))
I get the error :
504 5.7.4 Unrecognized authentication type
same if I put something in the UN/PW

**Comment by GuyBrand** [comment]
Good news !
and a question 

the news : I've figured it out :
I use the simple :
mailer := gomail.NewMailer("serverIp", "", "", 25)
1. on starttlsDial , I comment the  
	//if ok, _ := c.Extension("STARTTLS"); ok {
	//	fmt.Println("STARTTLS", err)
	//	return c, c.StartTLS(config)
	//}
cause you dont need TLS in this case .
2. on getSendMailFunc , I remarked :
		//if a != nil {
		//	fmt.Println("a!=nil ", err)
		//	if ok, _ := c.Extension("AUTH"); ok {
		//		if err = c.Auth(a); err != nil {
		//			return err
		//		}
		//	}
		//}

and I have an anonymous relay working .

question is :
would you like to implant that in  a nicer way on your code , so it will support whatever it does now , as well as the anonymous relay ?

   Guy .

**Comment by alexcesaro** [comment]
Ok I will have a look.

**Comment by alexcesaro** [comment]
Hello, it would be cool if you tried Gomail v2 (still unstable) and tell me if it works:

```go
package main

import (
	"gopkg.in/gomail.v2-unstable"
)

func main() {
	m := gomail.NewMessage()
	m.SetHeader("From", "from@example.com")
	m.SetHeader("To", "to@example.com")
	m.SetHeader("Subject", "Test")
	m.SetBody("text/html", "Test")

	d := gomail.NewPlainDialer("smtp.example.com", "user", "123456", 587)
	d.Auth = nil
	if err := d.DialAndSend(m); err != nil {
		panic(err)
	}
}
```

**Comment by alexcesaro** [comment]
I just edited my previous answer.

**Comment by GuyBrand** [comment]
Hi .

 

I'm off to a weekend , will do that early next week .

 

Thanks !

 

BTW , the current "workaround" is already in production .
