### ISSUE TITLE
Add Message-ID

### ISSUE THREAD

**Issue by tgulacsi** [go-gomail/gomail#36]
As per RFC822, email messages should have a Message-ID field. 
I know it's the message creator's responsibility, but at least we could help him by including a MakeMsgID function, as in https://github.com/tgulacsi/go/blob/master/i18nmail/msgid.go ?

If it's easier on you, I can send it as a PR, but first please vet this suggestion.

**Comment by alexcesaro** [comment]
Thanks for your suggestion but I don't want to add such a function. Here are the reasons:
- If I add MakeMsgID to help building the `Message-ID` field I cannot reject adding helper functions for all other headers.
- There is not a single way to implement MakeMsgID, different users may need different implementations.
- Implementing MakeMsgID is quite simple and only requires a small amount of code.

**Comment by vzool** [comment]
>     * Implementing MakeMsgID is quite simple and only requires a small amount of code.

@alexcesaro So, is this correct:
```go
message := gomail.NewMessage()
message.SetHeader("Message-ID", uuid.New().String())
```

**Comment by imqishi** [comment]
@vzool according to rfc 5322:
```
 The message identifier (msg-id) syntax is a limited version of the
   addr-spec construct enclosed in the angle bracket characters, "<" and
   ">".  Unlike addr-spec, this syntax only permits the dot-atom-text
   form on the left-hand side of the "@" and does not have internal CFWS
   anywhere in the message identifier.
```
so it's better to use
```golang
message.SetHeader("Message-ID", "<"+uuid.New().String()+">")
```
