### ISSUE TITLE
Erro TLS

### ISSUE THREAD

**Issue by jniltinho** [go-gomail/gomail#39]
undefined: tls in tls.Config

go build teste_email.go 
# command-line-arguments
./teste_email.go:16: undefined: tls in tls.Config

**Comment by alexcesaro** [comment]
Please explain what your problem is.

I guess you need to import [crypto/tls](https://golang.org/pkg/crypto/tls/) in your tests. You should use [goimports](https://github.com/bradfitz/goimports) to automatically manage your imports.

**Comment by jniltinho** [comment]
No build :-(

##Code

```go
package main

import (
    "gopkg.in/gomail.v2"
)

func main() {
    m := gomail.NewMessage()
    m.SetHeader("From", "nilton@domain.com")
    m.SetHeader("To", "nilton@domain2.com")
    m.SetHeader("Subject", "Hello!")
    m.SetBody("text/html", "Hello <b>Nilton OS</b>!")

    // Send the email to Bob
    d := gomail.NewPlainDialer("mail.domain.com", 587, "nilton@domain.com", "1234567")
    d.TLSConfig = &tls.Config{InsecureSkipVerify: true}
    if err := d.DialAndSend(m); err != nil {
        panic(err)
    }
}
```

**Comment by jniltinho** [comment]
:+1: 

Add lib "crypto/tls"

OK, 

Thank's

:-)

**Comment by alexcesaro** [comment]
You're welcome.

Which editor do you use? I greatly recommend using [goimports](https://github.com/bradfitz/goimports).

**Comment by pedromorgan** [comment]
Maybe add this to FAQ,, for new-go-users = muppets like me..  trying to swim

import "crypto/tls"
