### ISSUE TITLE
Expose Message.parts publicly?

### ISSUE THREAD

**Issue by Keats** [go-gomail/gomail#43]
It would be useful to have the parts exposed so we can test the body of an email (eg. is the correct activation link present in the email?).

What do you think?

**Comment by alexcesaro** [comment]
Have you tried using [Message.WriteTo](https://godoc.org/gopkg.in/gomail.v2#Message.WriteTo)?

You could use it with a bytes.Buffer or a custom writer that checks the content of the email.

**Comment by Keats** [comment]
Missed that, thanks!
