### ISSUE TITLE
AddAlternativeWriter replaces (does not add to) the parts

### ISSUE THREAD

**Issue by chowey** [go-gomail/gomail#44]
I am looking at [message.go](https://github.com/go-gomail/gomail/blob/v2/message.go#L213) and `AddAlternativeWriter` currently replaces (does not add to) the message parts. Shouldn't this do `append()` instead?

**Comment by alexcesaro** [comment]
That's right! I'm fixing that.

**Comment by alexcesaro** [comment]
Thank you. It is now fixed.
