### ISSUE TITLE
What is the correct way to make gomail work with go15vendorexperiment

### ISSUE THREAD

**Issue by sathishvj** [go-gomail/gomail#46]
Since go get does not currently support go15vendorexperiment, what is the right way to get this library?  And also to import it into the project?

Inside project/src/vendor do a 
```git clone --depth=1 https://github.com/go-gomail/gomail github.com/go-gomail/gomail```

then in code 
```
import "github.com/go-gomail/gomail"
```

It seems to work for me, but just wanted to make sure.

**Comment by alexcesaro** [comment]
Yes it should be alright since when using Go 1.5, Gomail does not import any external dependency.
