### ISSUE TITLE
Per-Part Content-Transfer-Encoding?

### ISSUE THREAD

**Issue by daBrado** [go-gomail/gomail#47]
I'd like to generate an email with a body and an attachment where each uses a different Content-Transfer-Encoding.  Is this possible?  It seems that each message part takes the value for the Content-Transfer-Encoding from the `Message` object's value for `encoding`, and are not independently settable.

Specifically, I want the body to have a Content-Type of "text/plain; format=flowed" with a Content-Transfer-Encoding of "8bit", and the attachment to have a Content-Type of "text/html" but with a Content-Transfer-Encoding of "quoted-printable".  (I'd rather not have the format=flowed text be encoded as quoted-printable, since RFC 3676 says that it "should not" be so.)

I'm fine with manually encoding the data I give to `SetBody` and `AddAlternative` as 8bit and quoted-printable, respectively; I just need to be able set the Content-Transfer-Encoding on a per-part basis.

Is there a way to do that now?  If not, does it seem like a reasonable thing to be able to do?

Thanks for any help.

**Comment by alexcesaro** [comment]
I am currently a bit busy but I'll have a look at this issue soon.

**Comment by alexcesaro** [comment]
That should be ok now using SetPartEncoding with SetBody or AddAlternative: https://godoc.org/github.com/go-gomail/gomail#example-SetPartEncoding

**Comment by daBrado** [comment]
Neat; thank you!
