### ISSUE TITLE
FormatAddress shouldn't insert empty quoted name

### ISSUE THREAD

**Issue by mackstann** [go-gomail/gomail#54]
When calling `FormatAddress` with an empty name, like:

    FormatAddress("foo@bar.com", "")

It returns:

    "" <foo@bar.com>

But it would be better to return:

    <foo@bar.com>

Normally it wouldn't matter all that much, but there is a bug in Go 1.5 and up that rejects such addresses with an error: https://github.com/golang/go/issues/14866

Removing the redundant `""` would greatly help work around this Go bug.

In the meantime, a hack like this will work around it:

    if name == "" {
        message.SetHeader("To", address) // bypass FormatAddress altogether
    } else {
        message.SetAddressHeader("To", address, name)
    }

**Comment by alexcesaro** [comment]
Fixed, thanks!

**Comment by mackstann** [comment]
Your fast action was very helpful to our team! Thank you!

**Comment by alexcesaro** [comment]
Glad it helped :smile:
