### ISSUE TITLE
closing amazon ses timeout returns "421 Timeout waiting for data from client"

### ISSUE THREAD

**Issue by sairam** [go-gomail/gomail#68]
`panic: 421 Timeout waiting for data from client.`

I am following the example from [the documentation](https://godoc.org/gopkg.in/gomail.v2#ex-package--Daemon) `Example (Daemon)` . Snippet
```go
			case <-time.After(30 * time.Second):
				if open {
					if err := s.Close(); err != nil {
						panic(err)
					}
					open = false
				}
```

I am seeing the following error - `panic: 421 Timeout waiting for data from client.` whenever the timeout gets invoked. 

When I remove the panic, The TCP connection failing to close goes into a `CLOSE_WAIT` leaving it about sometime

relevant file : https://github.com/go-gomail/gomail/blob/master/writeto.go

Operating System : OS X

**Comment by sairam** [comment]
Changing the timeout to 5 seconds (I am timing out at 4) solves the problem.

Not covered in AWS documentation as well. 

Thanks for the amazing library!

**Comment by akrantz01** [comment]
@sairam Where did you change the timeout?

**Comment by sairam** [comment]
I don't recall exactly where this is, but look at
https://github.com/sairam/kinli/blob/master/mailer.go#L79

The project I am using this library is at GitHub.com/Sairam/gitnotify
