### ISSUE TITLE
New Release Please

### ISSUE THREAD

**Issue by markbates** [go-gomail/gomail#94]
Hi, there hasn't been a new tagged release in nearly 2 years. Can you please create one so it works well with GitHub.com/golang/dep. Thanks.

**Comment by markbates** [comment]
@alexcesaro ping!

**Comment by PaluMacil** [comment]
this hasn't been maintained in a very long time. The accepted fork seems to have been https://github.com/go-mail/mail for a couple years now.

**Comment by Neustradamus** [comment]
Dear all, it is possible to change your code?
Change from here:
- https://github.com/go-gomail/gomail
- https://github.com/go-gomail/gomail/issues/188
- https://github.com/go-mail/mail
- https://github.com/Shopify/gomail
- https://github.com/Shopify/gomail/issues/59
- https://github.com/ory/mail

It has been unmaintained and maybe one or more vulnerabilities :/

There are:
- https://github.com/xhit/go-simple-mail from @xhit
- https://github.com/wneessen/go-mail from @wneessen

Linked to:
- https://github.com/go-gomail/gomail/issues/182
- https://github.com/go-gomail/gomail/issues/163
- https://github.com/go-gomail/gomail/issues/142
- https://github.com/go-gomail/gomail/issues/108
- https://github.com/go-gomail/gomail/issues/104
- https://github.com/go-gomail/gomail/issues/105
- https://github.com/go-gomail/gomail/issues/94
- https://github.com/go-mail/mail/issues/78
- https://github.com/go-mail/mail/issues/73
- https://github.com/go-mail/mail/issues/61
