### ISSUE TITLE
Need Help: How can I keep the connection alive instead of Dialling everytime?. 

### ISSUE THREAD

**Issue by astromahi** [go-gomail/gomail#96]
Can we handle the dial object like database handle so that I don't have to dial each time I send email?.

**Comment by jordan-wright** [comment]
Use `Dial` to get a `SendCloser` and then use that `SendCloser` when you call `Send`.

You can see an example (check out the "Newsletter" example) here: https://godoc.org/gopkg.in/gomail.v2#ex-package--Newsletter

**Comment by astromahi** [comment]
Thank you Jordan.
